class_name UITheme
extends RefCounted
## StyleBox factory for the menu look (docs/Examples/UI Menus mockups):
## wood-framed slot grids, steel-blue panels, wooden plaque titles.
## Textures are generated by tools/gen_placeholder_art.py into assets/ui/.

const DIR := "res://assets/ui/"
const FONT_SIZE := 8

static func _tex(name: String, margin: int) -> StyleBoxTexture:
	var sb := StyleBoxTexture.new()
	sb.texture = load(DIR + name + ".png")
	sb.texture_margin_left = margin
	sb.texture_margin_top = margin
	sb.texture_margin_right = margin
	sb.texture_margin_bottom = margin
	sb.content_margin_left = margin
	sb.content_margin_top = margin
	sb.content_margin_right = margin
	sb.content_margin_bottom = margin
	return sb

static func wood_frame() -> StyleBoxTexture:
	return _tex("wood_frame", 6)

static func steel_panel() -> StyleBoxTexture:
	return _tex("steel_panel", 4)

static func slot() -> StyleBoxTexture:
	return _tex("slot", 2)

static func slot_hover() -> StyleBoxTexture:
	return _tex("slot_hover", 2)

static func slot_selected() -> StyleBoxTexture:
	return _tex("slot_selected", 2)

static func steel_slot() -> StyleBoxTexture:
	return _tex("steel_slot", 2)

static func empty() -> StyleBoxEmpty:
	return StyleBoxEmpty.new()

## Wood slot button: normal / hover / pressed share the well look.
static func style_slot(b: Button, selected: bool = false) -> void:
	b.add_theme_stylebox_override("normal", slot_selected() if selected else slot())
	b.add_theme_stylebox_override("hover", slot_hover())
	b.add_theme_stylebox_override("pressed", slot_hover())
	b.add_theme_stylebox_override("focus", empty())

static func style_steel_slot(b: Button) -> void:
	b.add_theme_stylebox_override("normal", steel_slot())
	b.add_theme_stylebox_override("hover", _tex("steel_button_hover", 2))
	b.add_theme_stylebox_override("pressed", steel_slot())
	b.add_theme_stylebox_override("focus", empty())

static func style_button(b: Button) -> void:
	b.add_theme_stylebox_override("normal", _tex("steel_button", 3))
	b.add_theme_stylebox_override("hover", _tex("steel_button_hover", 3))
	b.add_theme_stylebox_override("pressed", _tex("steel_button_pressed", 3))
	b.add_theme_stylebox_override("disabled", _tex("steel_button_disabled", 3))
	b.add_theme_stylebox_override("focus", empty())
	b.add_theme_font_size_override("font_size", FONT_SIZE)
	b.add_theme_color_override("font_color", Color(0.9, 0.93, 0.95))
	b.add_theme_color_override("font_disabled_color", Color(0.5, 0.55, 0.6))
	b.focus_mode = Control.FOCUS_NONE

## Flat list row (recipe list): transparent, highlights on hover / when selected.
static func style_row(b: Button, selected: bool) -> void:
	var sel := StyleBoxFlat.new()
	sel.bg_color = Color(0.56, 0.75, 0.81, 0.25)
	sel.set_content_margin_all(2)
	var hov := StyleBoxFlat.new()
	hov.bg_color = Color(1, 1, 1, 0.08)
	hov.set_content_margin_all(2)
	var none := StyleBoxEmpty.new()
	none.set_content_margin_all(2)
	b.add_theme_stylebox_override("normal", sel if selected else none)
	b.add_theme_stylebox_override("hover", hov)
	b.add_theme_stylebox_override("pressed", sel)
	b.add_theme_stylebox_override("focus", empty())
	b.add_theme_font_size_override("font_size", FONT_SIZE)
	b.add_theme_color_override("font_color", Color(0.9, 0.93, 0.95))
	b.add_theme_color_override("font_disabled_color", Color(0.5, 0.55, 0.6))
	b.focus_mode = Control.FOCUS_NONE

static func label(text: String, size: int = FONT_SIZE, color: Color = Color(0.9, 0.93, 0.95)) -> Label:
	var l := Label.new()
	l.text = text
	l.add_theme_font_size_override("font_size", size)
	l.add_theme_color_override("font_color", color)
	l.mouse_filter = Control.MOUSE_FILTER_IGNORE
	return l
