class_name UITheme
extends RefCounted
## StyleBox factory for the menu look (docs/Examples/UI Menus mockups):
## wood-framed slot grids, steel-blue panels, wooden plaque titles.
## Textures are generated by tools/gen_placeholder_art.py into assets/ui/.

const DIR := "res://assets/ui/"
const FONT_SIZE := 8

static func _tex(name: String, margin: int) -> StyleBoxTexture:
	var sb := StyleBoxTexture.new()
	sb.texture = load(DIR + name + ".png")
	sb.texture_margin_left = margin
	sb.texture_margin_top = margin
	sb.texture_margin_right = margin
	sb.texture_margin_bottom = margin
	sb.content_margin_left = margin
	sb.content_margin_top = margin
	sb.content_margin_right = margin
	sb.content_margin_bottom = margin
	return sb

static func wood_frame() -> StyleBoxTexture:
	return _tex("wood_frame", 6)

static func steel_panel() -> StyleBoxTexture:
	return _tex("steel_panel", 4)

static func slot() -> StyleBoxTexture:
	return _tex("slot", 2)

static func slot_hover() -> StyleBoxTexture:
	return _tex("slot_hover", 2)

static func slot_selected() -> StyleBoxTexture:
	return _tex("slot_selected", 2)

static func steel_slot() -> StyleBoxTexture:
	return _tex("steel_slot", 2)

static func empty() -> StyleBoxEmpty:
	return StyleBoxEmpty.new()

## Wood slot button: normal / hover / pressed share the well look.
static func style_slot(b: Button, selected: bool = false) -> void:
	b.add_theme_stylebox_override("normal", slot_selected() if selected else slot())
	b.add_theme_stylebox_override("hover", slot_hover())
	b.add_theme_stylebox_override("pressed", slot_hover())
	b.add_theme_stylebox_override("focus", empty())

static func style_steel_slot(b: Button) -> void:
	b.add_theme_stylebox_override("normal", steel_slot())
	b.add_theme_stylebox_override("hover", _tex("steel_button_hover", 2))
	b.add_theme_stylebox_override("pressed", steel_slot())
	b.add_theme_stylebox_override("focus", empty())

static func style_button(b: Button) -> void:
	b.add_theme_stylebox_override("normal", _tex("steel_button", 3))
	b.add_theme_stylebox_override("hover", _tex("steel_button_hover", 3))
	b.add_theme_stylebox_override("pressed", _tex("steel_button_pressed", 3))
	b.add_theme_stylebox_override("disabled", _tex("steel_button_disabled", 3))
	b.add_theme_stylebox_override("focus", empty())
	b.add_theme_font_size_override("font_size", FONT_SIZE)
	b.add_theme_color_override("font_color", Color(0.9, 0.93, 0.95))
	b.add_theme_color_override("font_disabled_color", Color(0.5, 0.55, 0.6))
	b.focus_mode = Control.FOCUS_NONE

## Flat list row (recipe list): transparent, highlights on hover / when selected.
static func style_row(b: Button, selected: bool) -> void:
	var sel := StyleBoxFlat.new()
	sel.bg_color = Color(0.56, 0.75, 0.81, 0.25)
	sel.set_content_margin_all(2)
	var hov := StyleBoxFlat.new()
	hov.bg_color = Color(1, 1, 1, 0.08)
	hov.set_content_margin_all(2)
	var none := StyleBoxEmpty.new()
	none.set_content_margin_all(2)
	b.add_theme_stylebox_override("normal", sel if selected else none)
	b.add_theme_stylebox_override("hover", hov)
	b.add_theme_stylebox_override("pressed", sel)
	b.add_theme_stylebox_override("focus", empty())
	b.add_theme_font_size_override("font_size", FONT_SIZE)
	b.add_theme_color_override("font_color", Color(0.9, 0.93, 0.95))
	b.add_theme_color_override("font_disabled_color", Color(0.5, 0.55, 0.6))
	b.focus_mode = Control.FOCUS_NONE

## Flat panel with a visible steel-blue border — for full-screen menus
## (title) where the textured panels would fight the backdrop.
static func flat_panel(bg: Color = Color(0.06, 0.11, 0.16, 0.92)) -> StyleBoxFlat:
	var sb := StyleBoxFlat.new()
	sb.bg_color = bg
	sb.border_color = Color(0.32, 0.47, 0.55)
	sb.set_border_width_all(1)
	sb.set_content_margin_all(6)
	return sb

## Bordered text input: dark well, border brightens with focus.
static func style_input(e: LineEdit) -> void:
	var norm := StyleBoxFlat.new()
	norm.bg_color = Color(0.03, 0.06, 0.09)
	norm.border_color = Color(0.32, 0.47, 0.55)
	norm.set_border_width_all(1)
	norm.set_content_margin_all(4)
	var foc: StyleBoxFlat = norm.duplicate()
	foc.border_color = Color(0.56, 0.75, 0.81)
	e.add_theme_stylebox_override("normal", norm)
	e.add_theme_stylebox_override("focus", foc)
	e.add_theme_color_override("font_color", Color(0.9, 0.93, 0.95))
	e.add_theme_color_override("font_placeholder_color", Color(0.45, 0.53, 0.58))

## Bordered ItemList (title pickers): dark well, steel-blue selection bar,
## soft hover, no focus rectangle.
static func style_list(l: ItemList) -> void:
	var panel := StyleBoxFlat.new()
	panel.bg_color = Color(0.03, 0.06, 0.09)
	panel.border_color = Color(0.32, 0.47, 0.55)
	panel.set_border_width_all(1)
	panel.set_content_margin_all(4)
	l.add_theme_stylebox_override("panel", panel)
	var sel := StyleBoxFlat.new()
	sel.bg_color = Color(0.56, 0.75, 0.81, 0.3)
	sel.border_color = Color(0.56, 0.75, 0.81)
	sel.set_border_width_all(1)
	l.add_theme_stylebox_override("selected", sel)
	l.add_theme_stylebox_override("selected_focus", sel)
	var hov := StyleBoxFlat.new()
	hov.bg_color = Color(1, 1, 1, 0.07)
	l.add_theme_stylebox_override("hovered", hov)
	l.add_theme_stylebox_override("focus", empty())
	l.add_theme_color_override("font_color", Color(0.85, 0.89, 0.92))
	l.add_theme_color_override("font_hovered_color", Color(0.95, 0.97, 1.0))
	l.add_theme_color_override("font_selected_color", Color(0.97, 0.99, 1.0))

## Compact pixel-scale HSlider: dark groove, steel-blue fill, small grabber
## (the default theme grabber is huge against the 8px UI).
static func style_slider(s: HSlider) -> void:
	var groove := StyleBoxFlat.new()
	groove.bg_color = Color(0.03, 0.06, 0.09)
	groove.border_color = Color(0.32, 0.47, 0.55)
	groove.set_border_width_all(1)
	groove.content_margin_top = 3
	groove.content_margin_bottom = 3
	var fill := StyleBoxFlat.new()
	fill.bg_color = Color(0.56, 0.75, 0.81, 0.55)
	fill.content_margin_top = 3
	fill.content_margin_bottom = 3
	s.add_theme_stylebox_override("slider", groove)
	s.add_theme_stylebox_override("grabber_area", fill)
	s.add_theme_stylebox_override("grabber_area_highlight", fill)
	var img := Image.create(5, 9, false, Image.FORMAT_RGBA8)
	img.fill(Color(0.9, 0.93, 0.95))
	var grab := ImageTexture.create_from_image(img)
	s.add_theme_icon_override("grabber", grab)
	s.add_theme_icon_override("grabber_highlight", grab)
	s.add_theme_icon_override("grabber_disabled", grab)
	s.focus_mode = Control.FOCUS_NONE

static func label(text: String, size: int = FONT_SIZE, color: Color = Color(0.9, 0.93, 0.95)) -> Label:
	var l := Label.new()
	l.text = text
	l.add_theme_font_size_override("font_size", size)
	l.add_theme_color_override("font_color", color)
	l.mouse_filter = Control.MOUSE_FILTER_IGNORE
	return l
