"""Room template generator (CT-04/05): the proc-gen half of the authoring
workflow — run it (optionally with a new seed) until the library reads well,
then curate by hand-editing data/rooms.json. The game only ever consumes the
JSON; this tool never runs at play time.

Usage: python tools/gen_rooms.py [seed]
"""
import json
import random
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SEED = int(sys.argv[1]) if len(sys.argv) > 1 else 7

# Object widths (cells, 8 px each) must match data/objects.json sizes.
OBJ_W = {"bed_frame": 6, "cabinet": 4, "desk": 6, "chair": 2, "locker": 2,
         "fridge": 4, "med_cart": 4}
# Rooms are laid out on the 2-cell macro grid (the old 16 px lattice).
M = 2

# Type pools: (object id, weight)
POOLS = {
    "residential": [("bed_frame", 3), ("cabinet", 2), ("chair", 3), ("fridge", 2), ("desk", 1), ("locker", 1)],
    "office": [("desk", 4), ("chair", 4), ("cabinet", 2), ("locker", 2)],
    "business": [("desk", 4), ("chair", 3), ("cabinet", 2), ("locker", 1)],
    "hospital": [("med_cart", 3), ("bed_frame", 3), ("cabinet", 2), ("locker", 2), ("chair", 2)],
}
# Chance of a wood counter/shelf blocks strip per room, by type.
SHELF_CHANCE = {"residential": 0.35, "office": 0.3, "business": 0.3, "hospital": 0.25}


def make_room(rng, rtype, width, idx):
    objects = []
    x = M * rng.randint(0, 1)
    pool = POOLS[rtype]
    while x < width - 1:
        oid = rng.choices([p[0] for p in pool], weights=[p[1] for p in pool])[0]
        w = OBJ_W[oid]
        if x + w > width:
            break
        if rng.random() < 0.75:
            objects.append({"id": oid, "x": x})
            x += w + M * rng.randint(0, 2)
        else:
            x += M * rng.randint(1, 3)
    blocks = []
    if rng.random() < SHELF_CHANCE[rtype]:
        sx = M * rng.randint(1, max(1, width // M - 5))
        for k in range(rng.randint(2, 3)):  # wood shelf above the floor, one macro block per k
            for ox in range(M):
                for oy in range(M):
                    blocks.append({"mat": 2, "x": sx + k * M + ox, "dy": 2 * M + oy})
    zone = {"residential": "residential", "office": "commercial", "business": "business", "hospital": "civil"}[rtype]
    return {"id": "%s_%c" % (rtype, ord('a') + idx), "type": rtype, "zone": zone, "width": width,
            "height": 10, "depth_min": -9999, "depth_max": 9999,
            "objects": objects, "blocks": blocks}


def main():
    rng = random.Random(SEED)
    rooms = []
    for rtype in POOLS:
        for i in range(4):
            rooms.append(make_room(rng, rtype, rng.choice([16, 20, 24, 28]), i))
    out = ROOT / "data" / "rooms.json"
    payload = {
        "_comment": "Room template library (CT-04/05). Generated by tools/gen_rooms.py, then curated by hand — edits here are canonical. width = interior cells (8 px; tower floors hold 10 rows); objects x/blocks x are offsets from the room's west edge on the standing row; blocks dy = cells above the standing row; mat uses WorldGrid.M (2 = wood, 4 = plastic).",
        "rooms": rooms,
    }
    out.write_text(json.dumps(payload, indent=1) + "\n", encoding="utf-8")
    print("wrote", out, "-", len(rooms), "rooms (seed %d)" % SEED)


if __name__ == "__main__":
    main()
