"""Room template generator (CT-04/05): the proc-gen half of the authoring
workflow — run it (optionally with a new seed) until the library reads well,
then curate by hand-editing data/rooms.json. The game only ever consumes the
JSON; this tool never runs at play time.

Usage: python tools/gen_rooms.py [seed]
"""
import json
import random
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SEED = int(sys.argv[1]) if len(sys.argv) > 1 else 7

# Object widths must match data/objects.json sizes.
OBJ_W = {"bed_frame": 3, "cabinet": 2, "desk": 3, "chair": 1, "locker": 1,
         "fridge": 2, "med_cart": 2}

# Type pools: (object id, weight)
POOLS = {
    "residential": [("bed_frame", 3), ("cabinet", 2), ("chair", 3), ("fridge", 2), ("desk", 1), ("locker", 1)],
    "office": [("desk", 4), ("chair", 4), ("cabinet", 2), ("locker", 2)],
    "hospital": [("med_cart", 3), ("bed_frame", 3), ("cabinet", 2), ("locker", 2), ("chair", 2)],
}
# Chance of a wood counter/shelf blocks strip per room, by type.
SHELF_CHANCE = {"residential": 0.35, "office": 0.3, "hospital": 0.25}


def make_room(rng, rtype, width, idx):
    objects = []
    x = rng.randint(0, 1)
    pool = POOLS[rtype]
    while x < width - 1:
        oid = rng.choices([p[0] for p in pool], weights=[p[1] for p in pool])[0]
        w = OBJ_W[oid]
        if x + w > width:
            break
        if rng.random() < 0.75:
            objects.append({"id": oid, "x": x})
            x += w + rng.randint(0, 2)
        else:
            x += rng.randint(1, 3)
    blocks = []
    if rng.random() < SHELF_CHANCE[rtype]:
        sx = rng.randint(1, max(1, width - 5))
        for k in range(rng.randint(2, 3)):
            blocks.append({"mat": 2, "x": sx + k, "dy": 2})  # wood shelf above the floor
    zone = {"residential": "residential", "office": "commercial", "hospital": "hospital"}[rtype]
    return {"id": "%s_%c" % (rtype, ord('a') + idx), "type": rtype, "zone": zone, "width": width,
            "height": 5, "depth_min": -9999, "depth_max": 9999,
            "objects": objects, "blocks": blocks}


def main():
    rng = random.Random(SEED)
    rooms = []
    for rtype in POOLS:
        for i in range(4):
            rooms.append(make_room(rng, rtype, rng.choice([8, 10, 12, 14]), i))
    out = ROOT / "data" / "rooms.json"
    payload = {
        "_comment": "Room template library (CT-04/05). Generated by tools/gen_rooms.py, then curated by hand — edits here are canonical. width = interior cells; objects x/blocks x are offsets from the room's west edge on the standing row; blocks dy = cells above the standing row; mat uses WorldGrid.M (2 = wood, 4 = plastic).",
        "rooms": rooms,
    }
    out.write_text(json.dumps(payload, indent=1) + "\n", encoding="utf-8")
    print("wrote", out, "-", len(rooms), "rooms (seed %d)" % SEED)


if __name__ == "__main__":
    main()
