"""Master crafting table: every bench, its recipes and their costs.

    python tools/gen_crafting_doc.py      -> docs/Crafting.md

Reads data/recipes.json, data/items.json, data/objects.json. Re-run after any
recipe change; the "Proposed overhaul" section at the bottom is hand-written
in this script (PROPOSAL) and survives regeneration.
"""
import json
from collections import OrderedDict, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"
OUT = ROOT / "docs" / "Crafting.md"

STATION_ORDER = ["hand", "workbench", "forge", "med_station", "dive_station", "mod_bench"]
STATION_TITLE = {
    "hand": "By hand (no bench)", "workbench": "Workbench", "forge": "Forge",
    "med_station": "Med Station", "dive_station": "Dive Station", "mod_bench": "Modification Bench",
}


def load(name):
    return json.loads((DATA / name).read_text(encoding="utf-8"))


def main():
    items = {i["id"]: i for i in load("items.json")["items"]}
    objects = {o["id"]: o for o in load("objects.json")["objects"]}
    for oid, o in objects.items():
        items.setdefault(oid, {"id": oid, "name": o.get("name", oid), "category": "placeable_object"})
    recipes = load("recipes.json")["recipes"]

    def nm(i):
        return items.get(i, {}).get("name", i)

    by_station = defaultdict(list)
    for r in recipes:
        by_station[r["station"]].append(r)

    lines = []
    lines.append("# Crafting — master table\n")
    lines.append("*Generated by `python tools/gen_crafting_doc.py` from `data/recipes.json` "
                 "(%d recipes). Regenerate after any recipe change; the proposal at the bottom is kept by the script.*\n" % len(recipes))

    # Benches
    lines.append("## Benches\n")
    lines.append("| Bench | Object | Built from | Kind |")
    lines.append("|---|---|---|---|")
    station_objs = {o.get("station"): o for o in objects.values() if o.get("kind") == "station"}
    for st in STATION_ORDER:
        if st == "hand":
            lines.append("| By hand | — | — | no bench needed |")
            continue
        o = station_objs.get(st)
        cost = "—"
        for r in recipes:
            if r["output"]["item"] == (o or {}).get("id"):
                cost = ", ".join("%d %s" % (i["count"], nm(i["item"])) for i in r["inputs"]) + " @ " + STATION_TITLE.get(r["station"], r["station"])
        lines.append("| %s | `%s` | %s | crafting station |" % (STATION_TITLE[st], (o or {}).get("id", "?"), cost))
    for o in sorted((o for o in objects.values() if o.get("kind") == "scrapper"), key=lambda o: o.get("scrap_stage", 0)):
        cost = "—"
        for r in recipes:
            if r["output"]["item"] == o["id"]:
                cost = ", ".join("%d %s" % (i["count"], nm(i["item"])) for i in r["inputs"]) + " @ " + STATION_TITLE.get(r["station"], r["station"])
        lines.append("| %s | `%s` | %s | scrap bench (stage %d: bulk-grinds furniture) |" % (o["name"], o["id"], cost, int(o.get("scrap_stage", 0))))
    lines.append("")

    # Recipes per bench
    lines.append("## Recipes by bench\n")
    lines.append("Tier = the recipe's own tier tag. Known = available from the start (else taught by a schematic).\n")
    total_by_station = OrderedDict()
    for st in STATION_ORDER:
        rs = by_station.get(st, [])
        if not rs:
            continue
        total_by_station[st] = len(rs)
        lines.append("### %s (%d)\n" % (STATION_TITLE.get(st, st), len(rs)))
        lines.append("| Recipe | Makes | Tier | Known | Cost | Notes |")
        lines.append("|---|---|---|---|---|---|")
        for r in sorted(rs, key=lambda r: (int(r.get("tier", 0)), r["id"])):
            out = r["output"]
            cost = ", ".join("%d %s" % (i["count"], nm(i["item"])) for i in r["inputs"])
            notes = []
            if r.get("district_weapon"):
                notes.append("district weapon (gen_weapons.py)")
            if items.get(out["item"], {}).get("category") == "ammo":
                notes.append("ammo")
            if r.get("desc"):
                notes.append(r["desc"])
            lines.append("| `%s` | %s ×%d | %d | %s | %s | %s |" % (
                r["id"], nm(out["item"]), int(out["count"]), int(r.get("tier", 0)),
                "yes" if r.get("known") else "schematic", cost, "; ".join(notes)))
        lines.append("")

    # Material demand
    lines.append("## Material demand (sum of all recipe inputs)\n")
    demand = defaultdict(int)
    for r in recipes:
        for i in r["inputs"]:
            demand[i["item"]] += int(i["count"])
    lines.append("| Material | Total across recipes | Recipes using it |")
    lines.append("|---|---|---|")
    for mat, total in sorted(demand.items(), key=lambda kv: -kv[1]):
        users = sum(1 for r in recipes if any(i["item"] == mat for i in r["inputs"]))
        lines.append("| %s | %d | %d |" % (nm(mat), total, users))
    lines.append("")

    lines.append(PROPOSAL)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("wrote", OUT, "-", len(recipes), "recipes across", len(total_by_station), "benches")


PROPOSAL = """## Proposed overhaul (2026-09-06, not yet built)

The user wants the crafting menu rebuilt around more, narrower benches. Current
shape: 11 recipes by hand, the Workbench carries 55 (every wood/scrap tool,
weapon, ammo, block and station), the Forge 32, the Dive Station 6, the Med
Station 2, the Modification Bench none.
Proposal: keep the five stage stations as the spine, add three dedicated
benches, and move recipes by TYPE so each menu fits on one screen.

| Bench (new ✱) | Stage | Built from | Takes over |
|---|---|---|---|
| Workbench | 1 | 30 wood + 15 scrap (hand) | wood/scrap TOOLS, blocks, walls, ladders, rope, chests, lamps, the other benches |
| Weapon Bench ✱ | 1–2 | 20 wood + 20 scrap + 5 cloth @ Workbench | every melee recipe (`district_weapon`), bows/crossbows, spear gun, all ammo; later iron/steel melee still needs its ingot from the Forge/Steel Works |
| Forge | 2–3 | as now | scrap → iron smelting, iron tools/gear, iron melee, pistol/rifle rounds, rivets, the Iron scrap bench |
| Pump Works ✱ | 2–3 | 15 iron + 20 scrap + 10 plastic @ Forge | water pump, pipes/outlets, buckets, breakers, wired lights, the tanks' valves (moves the utility tail out of the Workbench / Dive Station) |
| Steel Works ✱ | 4–5 | 20 steel + 30 iron @ Forge (schematic-gated) | iron → steel, every steel recipe: cutting torch, hard suit, rebreather, steel melee, harpoons, the Steel/Master scrap benches |
| Med Station | 2 | as now | bandages, medkits, food prep |
| Dive Station | 2–3 | as now | suits, tanks, fins/masks; loses the pump |
| Modification Bench | 3 | as now | modifier library (no recipes) |

Rules of thumb for the move: a recipe goes to the bench of its OUTPUT's type,
not its input material; a bench never carries more than ~25 recipes; each new
bench is itself crafted one stage earlier than the recipes it unlocks, so the
progression is Workbench → Weapon Bench → Forge → Pump Works / Dive Station →
Steel Works. Data side: `station` on each recipe plus three station objects
(kind `station`, `station` key) and their sprites; `Data.STATIONS` grows by
three; `inventory_ui` crafting tabs are already station-filtered.
"""


if __name__ == "__main__":
    main()
